/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class BindingJava */

#ifndef _Included_BindingJava
#define _Included_BindingJava
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     BindingJava
     * Method:    CreateStyleOptionsInstance
     * Signature: ()J
     */
    JNIEXPORT jlong JNICALL Java_BindingJava_CreateStyleOptionsInstance
    (JNIEnv*, jobject);

    /*
     * Class:     BindingJava
     * Method:    CreateStyleWithStyleURL
     * Signature: (JLjava/lang/String;)J
     */
    JNIEXPORT jlong JNICALL Java_BindingJava_CreateStyleWithStyleURL
    (JNIEnv*, jobject, jlong, jstring);

    /*
     * Class:     BindingJava
     * Method:    DestroyStyleOptionsInstance
     * Signature: (J)V
     */
    JNIEXPORT void JNICALL Java_BindingJava_DestroyStyleOptionsInstance
    (JNIEnv*, jobject, jlong);

    /*
     * Class:     BindingJava
     * Method:    CreateMapInstance
     * Signature: ()J
     */
    JNIEXPORT jlong JNICALL Java_BindingJava_CreateMapInstance
    (JNIEnv*, jobject);

    /*
     * Class:     BindingJava
     * Method:    SetMapStyle
     * Signature: (JJ)J
     */
    JNIEXPORT jlong JNICALL Java_BindingJava_SetMapStyle
    (JNIEnv*, jobject, jlong, jlong);

    /*
     * Class:     BindingJava
     * Method:    RenderMap
     * Signature: (JLjava/lang/String;)V
     */
    JNIEXPORT void JNICALL Java_BindingJava_RenderMap
    (JNIEnv*, jobject, jlong, jstring);

    /*
     * Class:     BindingJava
     * Method:    DestroyMapInstance
     * Signature: (J)V
     */
    JNIEXPORT void JNICALL Java_BindingJava_DestroyMapInstance
    (JNIEnv*, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
